import product1 from "/public/productImages/product1.png";
import product2 from "/public/productImages/product2.png";
import product3 from "/public/productImages/product3.png";
import product4 from "/public/productImages/product4.png";
import product5 from "/public/productImages/product5.png";
import product6 from "/public/productImages/product6.png";
import product7 from "/public/productImages/product7.png";
import product8 from "/public/productImages/product8.png";

export default function prouductData() {
  const productData = [
    {
      id: 0,
      image: product1,
      title: "Apple iPhone 14 Pro Max",
      specifications: [
        ["Screen size", "6.7 Inches"],
        ["CPU", "apple a16 bionic"],
        ["Number of cores", "6"],
        ["Main camera", "48-12-12 MP"],
        ["Front camera", "12mp"],
        ["Battery capacity", "4323 mAh"],
        ["Screen resolution", "2796x1290"],
        ["Screen refresh rate", "120 Hz"],
        ["Pixel density", "460 ppi"],
        ["Screen type", "OLED"],
        [
          "Additionally",
          [
            "dynamic islan",
            "always on display",
            "HDR display",
            "ture tone",
            "wide color (p3)",
          ],
        ],
      ],
      detail: "Apple iPhone 14 Pro Max 128GB Deep Purple (MQ9T3RX/A)",
      description:
        "Enhanced capabilities thanks toan enlarged display of 6.7 inchesand work without rechargingthroughout the day. Incredible photosas in weak, yesand in bright lightusing the new systemwith two cameras",
      reviews: {
        excellent: 249,
        good: 150,
        average: 200,
        belowAverage: 100,
        poor: 5,
      },
      price: [900, 850],
      memory: ["128GB", "256GB", "512GB", "1TB"],
      colors: [
        "bg-[#ef4444]",
        "bg-[#facc15]",
        "bg-[#4ade80]",
        "bg-[#3b82f6]",
        "bg-[#efaccd]",
      ],

      category: "smart phone",
    },
    {
      id: 1,
      image: product2,
      title: "Cinema Camera 6k",
      specifications: [
        ["Screen size", "6.7 Inches"],
        ["CPU", "apple a16 bionic"],
        ["Number of cores", "6"],
        ["Main camera", "48-12-12 MP"],
        ["Front camera", "12mp"],
        ["Battery capacity", "4323 mAh"],
        ["Screen resolution", "2796x1290"],
        ["Screen refresh rate", "120 Hz"],
        ["Pixel density", "460 ppi"],
        ["Screen type", "OLED"],
        [
          "Additionally",
          [
            "dynamic islan",
            "always on display",
            "HDR display",
            "ture tone",
            "wide color (p3)",
          ],
        ],
      ],
      detail: "Blackmagic Pocket Cinema Camera 6k",
      description:
        "Enhanced capabilities thanks toan enlarged display of 6.7 inchesand work without rechargingthroughout the day. Incredible photosas in weak, yesand in bright lightusing the new systemwith two cameras",
      reviews: {
        excellent: 249,
        good: 150,
        average: 200,
        belowAverage: 100,
        poor: 5,
      },
      price: [900, 800],
      memory: ["128GB", "256GB", "512GB", "1TB"],
      colors: [
        "bg-[#ef4444]",
        "bg-[#facc15]",
        "bg-[#4ade80]",
        "bg-[#3b82f6]",
        "bg-[#efaccd]",
      ],
    },
    {
      id: 2,
      image: product3,
      title: "Apple Watch S9",
      specifications: [
        ["Screen size", "3.7 Inches"],
        ["CPU", "apple a16 bionic"],
        ["Number of cores", "2"],
        ["Main camera", "12- MP"],
        ["Front camera", "10mp"],
        ["Battery capacity", "2000 mAh"],
        ["Screen resolution", "1200x860"],
        ["Screen refresh rate", "90 Hz"],
        ["Pixel density", "300 ppi"],
        ["Screen type", "LED"],
        [
          "Additionally",
          [
            "dynamic islan",
            "always on display",
            "HDR display",
            "ture tone",
            "wide color (p3)",
          ],
        ],
      ],
      detail: "Apple Watch Series 9 GPS 41mm Starlight Aluminium Case",
      description:
        "Enhanced capabilities thanks toan enlarged display of 3.7 inchesand work without rechargingthroughout the day. Incredible photosas in weak, yesand in bright lightusing the new systemwith two cameras",
      reviews: {
        excellent: 149,
        good: 250,
        average: 225,
        belowAverage: 250,
        poor: 15,
      },
      price: [1000, 950],
      memory: ["128GB", "256GB", "512GB", "1TB"],
      colors: [
        "bg-[#ef4444]",
        "bg-[#facc15]",
        "bg-[#4ade80]",
        "bg-[#3b82f6]",
        "bg-[#efaccd]",
      ],
    },
    {
      id: 3,
      image: product4,
      title: "Apple AirPods",
      specifications: [
        ["Backup", "5 Hours"],
        ["Audio range", "5.5Amp"],
        ["Bluthoot", "6-Band"],
        ["Speakers", "3.2MM"],
        ["Connectivity", "5M"],
        ["Battery capacity", "4323 mAh"],
        ["Dimansions", "2796x1290"],
        ["Wifi connectivity", "120 Hz"],
        [
          "Additionally",
          [
            "dynamic islan",
            "always on display",
            "HDR display",
            "ture tone",
            "wide color (p3)",
          ],
        ],
      ],
      detail: "AirPods Max Silver",
      description:
        "Enhanced capabilities thanks toan enlarged display of 6.7 inchesand work without rechargingthroughout the day. Incredible photosas in weak, yesand in bright lightusing the new systemwith two cameras",
      reviews: {
        excellent: 726,
        good: 350,
        average: 1200,
        belowAverage: 900,
        poor: 150,
      },
      price: [750, 600],
      memory: ["128GB", "256GB", "512GB", "1TB"],
      colors: [
        "bg-[#efaaaa]",
        "bg-[#fa1ee5]",
        "bg-[#4e8550]",
        "bg-[#3b1186]",
        "bg-[#efa33c]",
      ],
    },
    {
      id: 4,
      image: product5,
      title: "Galaxy Watch 6 Classic",
      specifications: [
        ["Screen size", "4.7 Inches"],
        ["CPU", "apple a16 bionic"],
        ["Number of cores", "4"],
        ["Main camera", "48-12-12 MP"],
        ["Speakers", "12mp"],
        ["Battery capacity", "4323 mAh"],
        ["Screen resolution", "2796x1290"],
        ["Screen refresh rate", "120 Hz"],
        ["Pixel density", "460 ppi"],
        ["Screen type", "OLED"],
        [
          "Additionally",
          [
            "dynamic islan",
            "always on display",
            "HDR display",
            "ture tone",
            "wide color (p3)",
          ],
        ],
      ],
      detail: "Samsung Galaxy Watch 6 Classic 47mm Black",
      description:
        "Enhanced capabilities thanks toan enlarged display of 6.7 inchesand work without rechargingthroughout the day. Incredible photosas in weak, yesand in bright lightusing the new systemwith two cameras",
      reviews: {
        excellent: 749,
        good: 540,
        average: 320,
        belowAverage: 215,
        poor: 125,
      },
      price: [900, 850],
      memory: ["128GB", "256GB", "512GB", "1TB"],
      colors: ["bg-[#ef4444]", "bg-[#4ade80]", "bg-[#3b82f6]", "bg-[#efaccd]"],
    },
    {
      id: 5,
      image: product6,
      title: "Galaxy Z Fold 5 ",
      specifications: [
        ["Screen size", "6 Inches"],
        ["CPU", "apple a16 bionic"],
        ["Number of cores", "8"],
        ["Main camera", "64-12-12 MP"],
        ["Front camera", "48 MP"],
        ["Battery capacity", "4323 mAh"],
        ["Screen resolution", "2796x1290"],
        ["Screen refresh rate", "120 Hz"],
        ["Pixel density", "460 ppi"],
        ["Screen type", "OLED"],
        [
          "Additionally",
          [
            "dynamic islan",
            "always on display",
            "HDR display",
            "ture tone",
            "wide color (p3)",
          ],
        ],
      ],
      detail: "Galaxy Z Fold 5 Unlocked | 256GB | Phantom Black",
      description:
        "Enhanced capabilities thanks toan enlarged display of 6.7 inchesand work without rechargingthroughout the day. Incredible photosas in weak, yesand in bright lightusing the new systemwith two cameras",
      reviews: {
        excellent: 226,
        good: 220,
        average: 158,
        belowAverage: 354,
        poor: 25,
      },
      price: [900, 850],
      memory: ["128GB", "256GB", "512GB", "1TB"],
      colors: [
        "bg-[#ef4444]",
        "bg-[#facc15]",
        "bg-[#4ade80]",
        "bg-[#3b82f6]",
        "bg-[#efaccd]",
      ],
    },
    {
      id: 6,
      image: product7,
      title: "Galaxy Buds FEGraphite",
      specifications: [
        ["Screen size", "8 Inches"],
        ["CPU", "apple a16 bionic"],
        ["Number of cores", "12"],
        ["Main camera", "128-64-48 MP"],
        ["Front camera", "64 MP"],
        ["Battery capacity", "4323 mAh"],
        ["Screen resolution", "2796x1290"],
        ["Screen refresh rate", "120 Hz"],
        ["Pixel density", "460 ppi"],
        ["Screen type", "OLED"],
        [
          "Additionally",
          [
            "dynamic islan",
            "always on display",
            "HDR display",
            "ture tone",
            "wide color (p3)",
          ],
        ],
      ],
      detail: "Galaxy Buds FEGraphite",
      description:
        "Enhanced capabilities thanks toan enlarged display of 6.7 inchesand work without rechargingthroughout the day. Incredible photosas in weak, yesand in bright lightusing the new systemwith two cameras",
      reviews: {
        excellent: 349,
        good: 100,
        average: 200,
        belowAverage: 50,
        poor: 45,
      },
      price: [900],
      memory: ["128GB", "256GB", "512GB", "1TB"],
      colors: ["bg-[#facc15]", "bg-[#4ade80]", "bg-[#3b82f6]", "bg-[#efacc,d]"],
    },
    {
      id: 7,
      image: product8,
      title: "Apple iPad 9",
      specifications: [
        ["Screen size", "6.7 Inches"],
        ["CPU", "apple a16 bionic"],
        ["Number of cores", "6"],
        ["Main camera", "48-12-12 MP"],
        ["Front camera", "12mp"],
        ["Battery capacity", "4323 mAh"],
        ["Screen resolution", "2796x1290"],
        ["Screen refresh rate", "120 Hz"],
        ["Pixel density", "460 ppi"],
        ["Screen type", "OLED"],
        [
          "Additionally",
          [
            "dynamic islan",
            "always on display",
            "HDR display",
            "ture tone",
            "wide color (p3)",
          ],
        ],
      ],
      detail: "Apple iPad 9 10.2 64GB Wi-Fi Silver (MK2L3) 2021",
      description:
        "Enhanced capabilities thanks toan enlarged display of 6.7 inchesand work without rechargingthroughout the day. Incredible photosas in weak, yesand in bright lightusing the new systemwith two cameras",
      reviews: {
        excellent: 349,
        good: 550,
        average: 400,
        belowAverage: 250,
        poor: 75,
      },
      price: [500],
      memory: ["128GB", "256GB", "512GB", "1TB"],
      colors: [
        "bg-[#ef7744]",
        "bg-[#ec15]",
        "bg-[#4a9990]",
        "bg-[#3b56f6]",
        "bg-[#efa11d]",
      ],
    },
  ];

  return productData;
}
